### PR TITLE
Fixed compilation with GHC 7.4.2

### PR DESCRIPTION
**Pull request by asr**

### CODE REVIEW

**Comment by asr** [comment]
CC'ing @jonaprieto.

**Comment by asr** [comment]
BTW, I installed GHC 7.4.2 on my Ubuntu 16.04 using [this](https://launchpad.net/~hvr/+archive/ubuntu/ghc) PPA. @hvr, thanks for creating these Haskell related packages!

**Comment by kazkansouh** [comment]
Thank you for the fix, its merged now.

**Comment by asr** [comment]
Thanks for merging!

**Pull request merged**
